# NUMPY BASICS <hr style = "border:2.5px solid navy"></hr>


Data Analyst: Erol A. Amante <br>
Department: Electrical Department

# Measures of Central Tendency

In [128]:
# imports and packages
import numpy as np
from scipy import stats

In [129]:
# Asigning the array
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [130]:
# Finding the mean of the array
fruits_mean = np.mean(fruits)
fruits_mean

123.0

In [131]:
# Finding the median of the array
fruits_median = np.median(fruits)
fruits_median

120.0

In [132]:
# Finding the mode of the array
fruits_mode = stats.mode(fruits)
fruits_mode

ModeResult(mode=60, count=1)

# 1D Array

In [133]:
# Assigning a 1D Array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [134]:
# Assigning a 2D Array
array_b = np.array([
    [1,2,3],
    [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
# Transposing array into columns
array_b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [136]:
# Updating the Status 
array_b = array_b.T
array_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [137]:
array_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [138]:
# Adding by row 
np.sum(array_b, axis=0)

array([ 6, 15])

In [139]:
# Adding by column
np.sum(array_b, axis=1)

array([5, 7, 9])

# Exercise Jaguar VS. Panther 

## Jaguar Dataset

In [140]:
Jaguar = np.array([10.6, 9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
Jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [141]:
Jaguar_mean = np.mean(Jaguar)
print("The mean of the dataset Jaguar is " + str(Jaguar_mean))

Jaguar_median = np.median(Jaguar)
print("The median of the dataset Jaguar is " + str(Jaguar_median))

Jaguar_mode = stats.mode(Jaguar)
print("The mode of the dataset Jaguar is " + str(Jaguar_mode[0]) + " and the count is " + str(Jaguar_mode[1]))


The mean of the dataset Jaguar is 9.399999999999999
The median of the dataset Jaguar is 9.8
The mode of the dataset Jaguar is 9.8 and the count is 2


In [142]:
Jaguar_minrange = np.min(Jaguar)
print("The minimum range of the Jaguar dataset is " + str(Jaguar_minrange)) 

The minimum range of the Jaguar dataset is 3.0


In [143]:
Jaguar_maxrange = np.max(Jaguar)
print("The maximum range of the Jaguar dataset is " + str(Jaguar_maxrange)) 

The maximum range of the Jaguar dataset is 11.0


In [144]:
Jaguar_PQuart1 = np.percentile(Jaguar,25)
print("The 1st Quartile of the Jaguar Dataset is " + str(Jaguar_PQuart1))

The 1st Quartile of the Jaguar Dataset is 9.4


In [145]:
Jaguar_PQuart2 = np.percentile(Jaguar,50)
print("The 2nd Quartile of the Jaguar Dataset is " + str(Jaguar_PQuart2))

The 2nd Quartile of the Jaguar Dataset is 9.8


In [146]:
Jaguar_PQuart3 = np.percentile(Jaguar,75)
print("The 3rd Quartile of the Jaguar Dataset is " + str(Jaguar_PQuart3))

The 3rd Quartile of the Jaguar Dataset is 10.45


In [147]:
# Interquartile range
IQR_Jaguar = Jaguar_PQuart3 - Jaguar_PQuart1
print("The interquartile range of the Jaguar dataset is " + str(IQR_Jaguar))

The interquartile range of the Jaguar dataset is 1.049999999999999


In [148]:
Var_Jaguar = np.var(Jaguar)
print("The Variance of the Jaguar dataset is " + str(Var_Jaguar))

The Variance of the Jaguar dataset is 4.418181818181818


In [149]:
StD_Jaguar = np.std(Jaguar)
print("The Standard Deviation of the Jaguar dataset is " + str(StD_Jaguar))

The Standard Deviation of the Jaguar dataset is 2.101947149236112


## Panther Dataset

In [150]:
Panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
Panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [151]:
Panther_mean = np.mean(Panther)
print("The mean of the dataset Panther is " + str(Panther_mean))

Panther_median = np.median(Panther)
print("The median of the dataset Panther is " + str(Panther_median))

Panther_mode = stats.mode(Panther)
print("The mode of the dataset Panther is " + str(Panther_mode[0]) + " and the count is " + str(Panther_mode[1]))


The mean of the dataset Panther is 10.75
The median of the dataset Panther is 9.55
The mode of the dataset Panther is 9.1 and the count is 3


In [152]:
Panther_minrange = np.min(Panther)
print("The minimum range of the Panther dataset is ", Panther_minrange) 

The minimum range of the Panther dataset is  9.1


In [153]:
Panther_maxrange = np.max(Panther)
print("The maximum range of the Panther dataset is " + str(Panther_maxrange)) 

The maximum range of the Panther dataset is 20.0


In [154]:
Panther_PQuart1 = np.percentile(Panther,25)
print("The 1st Quartile of the Panther Dataset is " + str(Panther_PQuart1))

The 1st Quartile of the Panther Dataset is 9.125


In [155]:
Panther_PQuart2 = np.percentile(Panther,50)
print("The 2nd Quartile of the Panther Dataset is " + str(Panther_PQuart2))

The 2nd Quartile of the Panther Dataset is 9.55


In [156]:
Panther_PQuart3 = np.percentile(Panther,75)
print("The 3rd Quartile of the Panther Dataset is " + str(Panther_PQuart3))

The 3rd Quartile of the Panther Dataset is 10.625


In [157]:
# Interquartile range
IQR_Panther = Panther_PQuart3 - Panther_PQuart1
print("The interquartile range of the Panther dataset is " + str(IQR_Panther))

The interquartile range of the Panther dataset is 1.5


In [158]:
Var_Panther = np.var(Panther)
print("The Variance of the Panther dataset is " + str(Var_Panther))

The Variance of the Panther dataset is 9.974499999999999


In [159]:
StD_Panther = np.std(Panther)
print("The Standard Deviation of the Panther dataset is " + str(StD_Panther))

The Standard Deviation of the Panther dataset is 3.1582431825304393
